name: Build, Scan, Push, and Sign (ECR)

on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  contents: read

env:
  APP_DIR: apps/api-python-flask     # path that contains the Dockerfile
  IMAGE_TAG: latest                  # also tags every build with the commit SHA

jobs:
  build-scan-push-sign:
    runs-on: ubuntu-latest

    # Make critical values available to every step
    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      ECR_REPO_URI: ${{ secrets.ECR_REPO_URI }}
      AWS_KMS_KEY_ARN: ${{ secrets.AWS_KMS_KEY_ARN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials (access keys for now)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Sanity check env
        run: |
          echo "APP_DIR=${APP_DIR}"
          echo "ECR_REPO_URI=${ECR_REPO_URI}"
          test -n "$ECR_REPO_URI" || { echo "ECR_REPO_URI is empty"; exit 1; }

      - name: Build image
        working-directory: ${{ env.APP_DIR }}
        run: |
          docker build -t "${ECR_REPO_URI}:${IMAGE_TAG}" .
          docker tag  "${ECR_REPO_URI}:${IMAGE_TAG}" "${ECR_REPO_URI}:${GITHUB_SHA}"

      - name: Trivy scan (fail on CRITICAL)
        uses: aquasecurity/trivy-action@0.24.0
        with:
          image-ref: ${{ env.ECR_REPO_URI }}:${{ env.IMAGE_TAG }}
          format: 'table'
          exit-code: '1'
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
          ignore-unfixed: true

      - name: Install Syft
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh \
            | sh -s -- -b /usr/local/bin

      - name: Generate SBOM (CycloneDX JSON)
        run: |
          syft scan image:${{ env.ECR_REPO_URI }}:${{ env.IMAGE_TAG }} -o cyclonedx-json > sbom-${{ github.sha }}.json

      - name: Push image
        run: |
          docker push "${ECR_REPO_URI}:${IMAGE_TAG}"
          docker push "${ECR_REPO_URI}:${GITHUB_SHA}"

      - name: Install Cosign
        run: |
          curl -sSfL https://github.com/sigstore/cosign/releases/latest/download/cosign-linux-amd64 \
            -o /usr/local/bin/cosign
          chmod +x /usr/local/bin/cosign

      - name: Cosign sign (AWS KMS)
        env:
          COSIGN_EXPERIMENTAL: "true"
          COSIGN_YES: "true"
        run: |
          cosign sign --key "awskms://${AWS_KMS_KEY_ARN}" "${ECR_REPO_URI}:${IMAGE_TAG}"
          cosign sign --key "awskms://${AWS_KMS_KEY_ARN}" "${ECR_REPO_URI}:${GITHUB_SHA}"

      - name: Upload SBOM artifact
        uses: actions/upload-artifact@v4
        with:
          name: sbom-${{ github.sha }}
          path: sbom-${{ github.sha }}.json
